version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: Food
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4567
    ports:
      - "5432:5432"
    networks:
      - foodnet

  kafka:
    image: apache/kafka-native:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # Cluster & process roles (KRaft mode)
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
    networks:
      - foodnet

  food-restaurant:
    build:
      context: .
      dockerfile: Dockerfile
    image: food-restaurant-app
    container_name: food-restaurant
    depends_on:
      - postgres
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    networks:
      - foodnet

networks:
  foodnet:
    driver: bridge
